from HW_4.work_with_var_func_1 import *
from HW_4.str_func_2 import *
from HW_4.list_func_3 import *
from HW_4.logic_operations_func_4 import *
from HW_4.dictionaries_func_5 import *
from HW_4.preobrazovanie_func_6 import *
from HW_4.if_func_7 import *
from HW_4.for_func_8 import *
from HW_4.while_func_9 import *
